import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, CheckCircle2, CreditCard, MapPin } from "lucide-react";
import { useState } from "react";
import { formatPrice } from "../data/products";
import { useCart } from "../context/CartContext";

export default function Checkout() {
  const {cart,subtotal,shipping,total}=useCart(); const navigate=useNavigate(); const [placed,setPlaced]=useState(false);
  if(!cart.length) return <main className="page"><div className="container empty-state"><h2>Your cart is empty</h2><Link className="btn btn-primary" to="/products">Shop now</Link></div></main>;
  if(placed) return <main className="page"><div className="container"><div className="empty-state large"><div className="success-icon"><CheckCircle2/></div><h2>Order placed successfully!</h2><p>Your demo order has been created. In the connected version, this will be saved through your Spring Boot API.</p><button className="btn btn-primary" onClick={()=>navigate("/orders")}>View orders</button></div></div></main>;
  return <main className="page"><div className="container"><div className="breadcrumb"><Link to="/cart">Cart</Link><span>/</span><span>Checkout</span></div><div className="checkout-layout"><section><div className="checkout-title"><span className="eyebrow small">Almost there</span><h1>Checkout</h1></div><div className="checkout-card"><h3><MapPin size={18}/> Delivery address</h3><div className="form-grid"><label>Full name<input placeholder="Kaya Vineel Kumar"/></label><label>Phone number<input placeholder="+91 98765 43210"/></label><label className="wide">Address<input placeholder="House / flat number, street"/></label><label>City<input placeholder="Hyderabad"/></label><label>PIN code<input placeholder="500001"/></label></div></div><div className="checkout-card"><h3><CreditCard size={18}/> Payment method</h3><label className="payment-option"><input type="radio" defaultChecked name="pay"/> <span><strong>Cash on delivery</strong><small>Pay when your order arrives</small></span></label><label className="payment-option"><input type="radio" name="pay"/> <span><strong>Card / UPI</strong><small>Secure online payment</small></span></label></div></section><aside className="summary"><h2>Review order</h2>{cart.map(i=><div className="review-line" key={i.id}><span>{i.name} × {i.quantity}</span><strong>{formatPrice(i.price*i.quantity)}</strong></div>)}<div><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><div><span>Shipping</span><strong>{shipping===0?"FREE":formatPrice(shipping)}</strong></div><div className="summary-total"><span>Total</span><strong>{formatPrice(total)}</strong></div><button className="btn btn-primary full" onClick={()=>setPlaced(true)}>Place order <ArrowLeft size={17} className="rotate-180"/></button></aside></div></div></main>;
}